import turtle

adrian = turtle.Turtle()
scn = turtle.Screen()
bob = turtle.Turtle()
jack = turtle.Turtle()

bob.speed(100)
bob.penup()
bob.goto(-200, -200)
bob.right(45)
bob.pendown()
bob.color("yellow")
bob.begin_fill()
bob.circle(300)
bob.end_fill()


def semicircle():
    for i in range(4):
        turtle.forward(10)
        turtle.right(45)


jack.penup()
jack.goto(298, 100)
jack.right(180)
jack.pendown()
jack.begin_fill()
jack.forward(275)
jack.left(90)
jack.forward(50)
jack.left(45)
jack.forward(45)
jack.left(45)
jack.forward(210)
jack.left(45)
jack.forward(45)
jack.left(45)
jack.forward(50)
jack.end_fill()

adrian.penup()
adrian.goto(-273, 100)
adrian.pendown()
adrian.forward(275)
adrian.begin_fill()
adrian.right(90)
adrian.forward(50)
adrian.right(45)
adrian.forward(45)
adrian.right(45)
adrian.forward(210)
adrian.right(45)
adrian.forward(45)
adrian.right(45)
adrian.forward(50)
adrian.end_fill()

turtle.exitonclick()
